# Generated by Django 2.1.4 on 2019-08-23 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190823_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragearchived',
            name='ActiveVersion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Coverage'),
        ),
        migrations.AddField(
            model_name='coveragearchived',
            name='ArchiveStatus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.ApplicationStatus'),
        ),
        migrations.AlterField(
            model_name='collateralarchived',
            name='ArchiveStatus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.ApplicationStatus'),
        ),
        migrations.AlterField(
            model_name='depositarchived',
            name='ArchiveStatus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.ApplicationStatus'),
        ),
    ]
