# Generated by Django 2.1.4 on 2019-08-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190823_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchtemplates',
            options={'verbose_name': 'SearchTemplates'},
        ),
        migrations.AlterModelTable(
            name='searchtemplates',
            table='SearchTemplates',
        ),
    ]
