# Generated by Django 2.1.4 on 2019-08-29 08:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20190828_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collateralarchived',
            name='Description3',
        ),
        migrations.RemoveField(
            model_name='collateralarchived',
            name='Description4',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='Description3',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='Description4',
        ),
        migrations.RemoveField(
            model_name='depositarchived',
            name='Description3',
        ),
        migrations.RemoveField(
            model_name='depositarchived',
            name='Description4',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='Description3',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='Description4',
        ),
        migrations.RemoveField(
            model_name='facilityarchived',
            name='Description3',
        ),
        migrations.RemoveField(
            model_name='facilityarchived',
            name='Description4',
        ),
        migrations.AlterField(
            model_name='collateralarchived',
            name='Description1',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collateralarchived',
            name='Description2',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='Description1',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='Description2',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facilityarchived',
            name='Description1',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facilityarchived',
            name='Description2',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
