from common.serializers.communication.communication import CommunicationSerializer
from common.serializers.communication.communication_attachment import CommunicationAttachmentSerializer
from common.serializers.communication.communications import CommunicationsSerializer
